#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -l log.blockMesh.solid blockMesh -region solid
runApplication -l log.blockMesh.fluid blockMesh -region fluid

# Run serial
runApplication solids4Foam


# ----------------------------------------------------------------- end-of-file

