#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

foamClearPolyMesh -region fluid
foamClearPolyMesh -region solid

\rm -rf constant/polyMesh
\rm -rf constant/solid/polyMesh
\rm -rf constant/fluid/polyMesh

cleanCase
cleanCase fluid
cleanCase solid

\rm -rf history
\rm -rf case.foam
