#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir constant/solid/polyMesh
runApplication -l log.fluent3DMeshToFoam.solid fluent3DMeshToFoam solid.msh
\mv constant/polyMesh/* constant/solid/polyMesh/
runApplication -l log.changeDictionary.solid changeDictionary -region solid
runApplication -l log.setSet.solid setSet -region solid -batch setBatch.solid
runApplication -l log.setsToZones.solid setsToZones -region solid -noFlipMap

mkdir constant/fluid/polyMesh
runApplication fluent3DMeshToFoam fluid.msh
\mv constant/polyMesh/* constant/fluid/polyMesh/
runApplication changeDictionary -region fluid
runApplication -l log.setSet.fluid setSet -region fluid -batch setBatch.fluid
runApplication -l log.setsToZones.fluid setsToZones -region fluid -noFlipMap

# Run serial
runApplication solids4Foam


# ----------------------------------------------------------------- end-of-file

