#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create the mesh
runApplication blockMesh
\mv log.blockMesh log.blockMesh.fluid

runApplication blockMesh -region solid
\mv log.blockMesh log.blockMesh.solid

# Run the solver in serial
#runApplication fsiFoam

# Decompose the mesh
runApplication decomposePar
\mv log.decomposePar log.decomposePar.fluid

runApplication decomposePar -region solid
\mv log.decomposePar log.decomposePar.solid

# Run the solver in parallel
runParallel fsiFoam 4

# Reconstruct the results
runApplication reconstructPar
\mv log.reconstructPar log.reconstructPar.fluid

runApplication reconstructPar -region solid
\mv log.reconstructPar log.reconstructPar.solid


# ----------------------------------------------------------------- end-of-file

